% -------------------------------------------------------------------
%  Generated by MATLAB on 28-Aug-2025 09:42:08
%  MATLAB version: 25.1.0.2952844 (R2025a)
% -------------------------------------------------------------------
saveVarsMat = load('matlab.mat');

Fs = 44100;

audioData = saveVarsMat.audioData; % <220500x1 double> too many elements

bboxes = [292 187 196 196];

faceDetector = saveVarsMat.faceDetector; % <1x1 vision.CascadeObjectDetector> unsupported class

imageData = saveVarsMat.imageData; % <480x640x3 uint8> too many elements

player = saveVarsMat.player; % <1x1 audioplayer> unsupported class

recObj = saveVarsMat.recObj; % <1x1 audiorecorder> unsupported class

clear saveVarsMat;
